# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns_manager', '0006_auto_20151018_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmetadata',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
    ]
